//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANEO
    {
        public int id { get; set; }
        public int idusuario { get; set; }
        public int idsuperusuario { get; set; }
        public string razonbaneo { get; set; }
        public string gravedad { get; set; }
        public System.DateTime fechainiciobaneo { get; set; }
        public Nullable<System.DateTime> fechafinbaneo { get; set; }
        public string activo { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
