//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIOS
    {
        public int id { get; set; }
        public int idcomentariocurso { get; set; }
        public string titulo { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual COMENTARIO_CURSO COMENTARIO_CURSO { get; set; }
    }
}
