//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.COMENTARIO_CURSO = new HashSet<COMENTARIO_CURSO>();
            this.MATERIAL = new HashSet<MATERIAL>();
            this.PREGUNTA_CURSO = new HashSet<PREGUNTA_CURSO>();
            this.RESPUESTA_CURSO = new HashSet<RESPUESTA_CURSO>();
            this.SUBIR_CURSO = new HashSet<SUBIR_CURSO>();
        }
    
        public int id { get; set; }
        public string titulodelcurso { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual ICollection<COMENTARIO_CURSO> COMENTARIO_CURSO { get; set; }
        public virtual ICollection<MATERIAL> MATERIAL { get; set; }
        public virtual ICollection<PREGUNTA_CURSO> PREGUNTA_CURSO { get; set; }
        public virtual ICollection<RESPUESTA_CURSO> RESPUESTA_CURSO { get; set; }
        public virtual ICollection<SUBIR_CURSO> SUBIR_CURSO { get; set; }
    }
}
