//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public int id { get; set; }
        public int idcurso { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
