//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA_CURSO
    {
        public PREGUNTA_CURSO()
        {
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.RESPUESTA_CURSO = new HashSet<RESPUESTA_CURSO>();
        }
    
        public int id { get; set; }
        public int idusuario { get; set; }
        public int idcurso { get; set; }
        public System.TimeSpan hora { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<RESPUESTA_CURSO> RESPUESTA_CURSO { get; set; }
    }
}
