//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPVIREntities : DbContext
    {
        public PPVIREntities()
            : base("name=PPVIREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANEO> BANEO { get; set; }
        public DbSet<COMENTARIO_CURSO> COMENTARIO_CURSO { get; set; }
        public DbSet<COMENTARIOS> COMENTARIOS { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<MATERIAL> MATERIAL { get; set; }
        public DbSet<PREGUNTA> PREGUNTA { get; set; }
        public DbSet<PREGUNTA_CURSO> PREGUNTA_CURSO { get; set; }
        public DbSet<RESPUESTA_CURSO> RESPUESTA_CURSO { get; set; }
        public DbSet<ROLES> ROLES { get; set; }
        public DbSet<SESION> SESION { get; set; }
        public DbSet<SUBIR_CURSO> SUBIR_CURSO { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<USUARIOENROLES> USUARIOENROLES { get; set; }
    }
}
