//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public ROLES()
        {
            this.USUARIOENROLES = new HashSet<USUARIOENROLES>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string detalles { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
    
        public virtual ICollection<USUARIOENROLES> USUARIOENROLES { get; set; }
    }
}
