//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESION
    {
        public int id { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string estado { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
