//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.BANEO = new HashSet<BANEO>();
            this.BANEO1 = new HashSet<BANEO>();
            this.COMENTARIO_CURSO = new HashSet<COMENTARIO_CURSO>();
            this.PREGUNTA_CURSO = new HashSet<PREGUNTA_CURSO>();
            this.SESION = new HashSet<SESION>();
            this.SUBIR_CURSO = new HashSet<SUBIR_CURSO>();
            this.USUARIOENROLES = new HashSet<USUARIOENROLES>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }

        public string apellidos { get; set; }
        public System.DateTime fechanacimiento { get; set; }
        public string email { get; set; }
        public string avatar { get; set; }
        public string nick { get; set; }
        public string contrasena { get; set; }
        public string carrera { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual ICollection<BANEO> BANEO { get; set; }
        public virtual ICollection<BANEO> BANEO1 { get; set; }
        public virtual ICollection<COMENTARIO_CURSO> COMENTARIO_CURSO { get; set; }
        public virtual ICollection<PREGUNTA_CURSO> PREGUNTA_CURSO { get; set; }
        public virtual ICollection<SESION> SESION { get; set; }
        public virtual ICollection<SUBIR_CURSO> SUBIR_CURSO { get; set; }
        public virtual ICollection<USUARIOENROLES> USUARIOENROLES { get; set; }
    }
}
